CREATE ROW ACCESS POLICY customer_policy
  AS (user_role STRING) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() = 'ANALYST' THEN TRUE
    WHEN CURRENT_ROLE() = 'CUSTOMER_ROLE' 
         AND user_role = CURRENT_USER() THEN TRUE
    ELSE FALSE
  END;

ALTER TABLE F1_ANALYTICS.GOLD.QUALIFICATION_RESULTS ADD ROW ACCESS POLICY CUSTOMER_POLICY ON (SESSION_KEY);
