
CREATE OR REPLACE TABLE F1_ANALYTICS.GOLD.QUALIFICATION_RESULTS
AS (SELECT 
SESSION_KEY
,POSITION
,NUMBER_OF_LAPS
,DNF
,DNS
,DSQ
,DRIVER_NUMBER
,Q1_TIMING
,Q2_TIMING
,Q3_TIMING
,CASE WHEN Q1_TIMING IS NULL THEN 0 ELSE 1 END AS HAS_Q1
,CASE WHEN Q2_TIMING IS NULL THEN 0 ELSE 1 END AS HAS_Q2
,CASE WHEN Q3_TIMING IS NULL THEN 0 ELSE 1 END AS HAS_Q3
,(
    (
    COALESCE(Q1_TIMING, 0)+ COALESCE(Q2_TIMING, 0) + COALESCE(Q3_TIMING, 0)
    )
    /
    (
    COALESCE(HAS_Q1, 0)+COALESCE(HAS_Q2, 0)+COALESCE(HAS_Q3, 0)
    )
    )::DECIMAL(10,3) 
    AS AVG_QUALI_TIME
,LEAST(
    COALESCE(Q1_TIMING, 999)
    ,COALESCE(Q2_TIMING, 999)
    ,COALESCE(Q3_TIMING, 999)
    ) AS FASTEST_QUALIFYING_TIME
,CASE WHEN POSITION <= 3 THEN 1 ELSE 0 END AS WINNER_FALG
FROM F1_ANALYTICS.SILVER.QUALIFYING_RESULTS);



CREATE OR REPLACE TABLE F1_ANALYTICS.GOLD.DRIVERS AS (
    SELECT * FROM F1_ANALYTICS.SILVER.DRIVERS
);
CREATE OR REPLACE TABLE F1_ANALYTICS.GOLD.SESSIONS AS (
    SELECT * FROM F1_ANALYTICS.SILVER.SESSIONS
);
CREATE OR REPLACE TABLE F1_ANALYTICS.GOLD.MEETINGS_SEASON_2026 AS (
    SELECT * FROM F1_ANALYTICS.SILVER.MEETINGS_SEASON_2026
);

CREATE OR REPLACE TABLE F1_ANALYTICS.GOLD.RECENT_MEETINGS AS (
    SELECT 
        DISTINCT(M.MEETING_KEY)
        ,M.MEETING_NAME 
        FROM F1_ANALYTICS.SILVER.QUALIFYING_RESULTS Q 
        JOIN F1_ANALYTICS.SILVER.MEETINGS_SEASON_2026 M ON M.MEETING_KEY = Q.MEETING_KEY
);
