USE F1_ANALYTICS.RAW;

CREATE OR REPLACE TABLE F1_ANALYTICS.RAW.DRIVERS
(
    RAW_LOGS VARIANT
);
CREATE OR REPLACE TABLE F1_ANALYTICS.RAW.RESULTS
(
    RAW_LOGS VARIANT
);
CREATE OR REPLACE TABLE F1_ANALYTICS.RAW.SESSIONS
(
    RAW_LOGS VARIANT
);
CREATE OR REPLACE TABLE F1_ANALYTICS.RAW.MEETINGS
(
    RAW_LOGS VARIANT
);


COPY INTO F1_ANALYTICS.RAW.DRIVERS 
FROM
@F1_ANALYTICS_DATA_STAGE/Data/Drivers/
FILE_FORMAT = (FORMAT_NAME = 'FF_JSON');

COPY INTO F1_ANALYTICS.RAW.RESULTS 
FROM
@F1_ANALYTICS_DATA_STAGE/Data/Results/
FILE_FORMAT = (FORMAT_NAME = 'FF_JSON');

COPY INTO F1_ANALYTICS.RAW.SESSIONS 
FROM
@F1_ANALYTICS_DATA_STAGE/Data/Sessions/
FILE_FORMAT = (FORMAT_NAME = 'FF_JSON');

COPY INTO F1_ANALYTICS.RAW.MEETINGS 
FROM
@F1_ANALYTICS_DATA_STAGE/Data/Meetings/
FILE_FORMAT = (FORMAT_NAME = 'FF_JSON');

CREATE OR REPLACE TABLE F1_ANALYTICS.BRONZE.DRIVER
AS(
    SELECT
     RAW_LOGS : broadcast_name :: text as BROADCAST_NAME
    ,RAW_LOGS : country_code :: text as COUNTRY_CODE
    ,RAW_LOGS : driver_number :: text as DRIVER_NUMBER
    ,RAW_LOGS : first_name :: text as FIRST_NAME
    ,RAW_LOGS : full_name :: text as FULL_NAME
    ,RAW_LOGS : last_name :: text as LAST_NAME
    ,RAW_LOGS : name_acronym :: text AS NAME_ACRONYM
    ,RAW_LOGS : team_name :: text AS TEAM_NAME
    ,RAW_LOGS : team_colour :: text AS TEAM_COLOUR
    ,RAW_LOGS : headshot_url :: text AS HEADSHOT_URL
    ,RAW_LOGS : session_key :: NUMBER AS SESSION_KEY

    FROM F1_ANALYTICS.RAW.DRIVERS 
);

CREATE OR REPLACE TABLE F1_ANALYTICS.BRONZE.RESULTS 
AS (
    SELECT
     RAW_LOGS : session_key :: NUMBER AS SESSION_KEY
    ,RAW_LOGS : meeting_key :: NUMBER AS MEETING_KEY 
    ,RAW_LOGS : dnf :: boolean AS DNF
    ,RAW_LOGS : dns :: boolean AS DNS
    ,RAW_LOGS : dsq :: boolean AS DSQ
    ,RAW_LOGS : driver_number :: text AS DRIVER_NUMBER
    ,RAW_LOGS : duration AS DURATION
    ,RAW_LOGS : gap_to_leader AS GAP_TO_LEADER
    ,RAW_LOGS : position :: number AS POSITION
    ,RAW_LOGS : number_of_laps :: number AS NUMBER_OF_LAPS
    
    FROM F1_ANALYTICS.RAW.RESULTS 
);

CREATE OR REPLACE TABLE F1_ANALYTICS.BRONZE.SESSIONS
AS (
    SELECT 
    RAW_LOGS : meeting_key :: NUMBER AS MEETING_KEY
   ,RAW_LOGS : session_key :: NUMBER AS SESSION_KEY
   ,RAW_LOGS : circuit_key :: NUMBER AS CIRCUIT_KEY
   ,RAW_LOGS : circuit_short_name :: TEXT AS CIRCUIT_SHORT_NAME
   ,RAW_LOGS : country_code :: TEXT AS COUNTRY_CODE
   ,RAW_LOGS : country_key :: NUMBER AS COUNTRY_KEY
   ,RAW_LOGS : country_name :: TEXT AS COUNTRY_NAME
   ,RAW_LOGS : date_end :: DATETIME AS DATE_END
   ,RAW_LOGS : date_start :: DATETIME DATE_START
   ,RAW_LOGS : gmt_offset :: TEXT AS GMT_OFFSE
   ,RAW_LOGS : location :: TEXT AS LOCATION
   ,RAW_LOGS : session_name :: TEXT AS SESSION_NAME
   ,RAW_LOGS : session_type :: TEXT AS SESSSION_TYPE
   ,RAW_LOGS : year :: NUMBER AS YEAR
   
    FROM F1_ANALYTICS.RAW.SESSIONS
);

CREATE OR REPLACE TABLE F1_ANALYTICS.BRONZE.MEETINGS 
AS(
    SELECT
    RAW_LOGS : circuit_key :: NUMBER AS CIRCUIT_KEY
   ,RAW_LOGS : circuit_info_url :: TEXT AS CIRCUIT_INFO_URL
   ,RAW_LOGS : circuit_image :: TEXT AS CIRCUIT_IMAGE
   ,RAW_LOGS : circuit_short_name :: TEXT AS CIRCUIT_SHORT_NAME
   ,RAW_LOGS : country_code :: TEXT AS COUNTRY_CODE
   ,RAW_LOGS : country_flag :: TEXT AS COUNTRY_FLAG
   ,RAW_LOGS : country_key :: NUMBER AS COUNTRY_KEY
   ,RAW_LOGS : country_name :: TEXT AS COUNTRY_NAME
   ,RAW_LOGS : date_end :: DATETIME AS DATE_END
   ,RAW_LOGS : date_start :: DATETIME AS DATE_START
   ,RAW_LOGS : gmt_offset :: TEXT AS GMT_OFFSET
   ,RAW_LOGS : location :: TEXT AS LOCATION
   ,RAW_LOGS : meeting_key :: NUMBER AS MEETING_KEY
   ,RAW_LOGS : meeting_name :: TEXT AS MEETING_NAME
   ,RAW_LOGS : meeting_official_name :: TEXT AS MEETING_OFFICIAL_NAME
   ,RAW_LOGS : year :: NUMBER AS YEAR

   FROM F1_ANALYTICS.RAW.MEETINGS
);
