-- DRIVER TABLE CLEANUP
CREATE OR REPLACE TABLE F1_ANALYTICS.SILVER.DRIVERS 
AS
(
SELECT 
     BROADCAST_NAME
    ,DRIVER_NUMBER
    ,CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME 
    ,NAME_ACRONYM
    ,TEAM_NAME
    ,HEADSHOT_URL
    FROM F1_ANALYTICS.BRONZE.DRIVER
 );

--RESULTS TABLE CLEANUP 
CREATE OR REPLACE TABLE F1_ANALYTICS.SILVER.QUALIFYING_RESULTS
AS
(
    SELECT 
         R.SESSION_KEY
        ,R.MEETING_KEY
        ,S.CIRCUIT_KEY
        ,S.CIRCUIT_SHORT_NAME
        ,S.COUNTRY_CODE
        ,DNF
        ,DNS
        ,DSQ 
        ,D.DRIVER_NUMBER
        ,D.FULL_NAME
        ,R.DURATION[0]::FLOAT AS Q1_TIMING
        ,R.DURATION[1]::FLOAT AS Q2_TIMING
        ,R.DURATION[2]::FLOAT AS Q3_TIMING
        ,R.GAP_TO_LEADER[0]::FLOAT AS Q1_GLT
        ,R.GAP_TO_LEADER[1]::FLOAT AS Q2_GLT
        ,R.GAP_TO_LEADER[2]::FLOAT AS Q3_GLT
        ,R.POSITION
        ,R.NUMBER_OF_LAPS
    FROM F1_ANALYTICS.BRONZE.RESULTS R
    JOIN F1_ANALYTICS.BRONZE.SESSIONS S 
    ON S.SESSION_KEY = R.SESSION_KEY
    JOIN F1_ANALYTICS.SILVER.DRIVERS D 
    ON D.DRIVER_NUMBER = R.driver_number 
    HAVING
    S.SESSSION_TYPE = 'Qualifying' 
    AND 
    S.SESSION_NAME = 'Qualifying'
);

SELECT * FROM F1_ANALYTICS.SILVER.DRIVERS;
SELECT * FROM F1_ANALYTICS.BRONZE.SESSIONS;
SELECT * FROM F1_ANALYTICS.SILVER.QUALIFYING_RESULTS;


--sessions table cleanup 
CREATE OR REPLACE TABLE F1_ANALYTICS.SILVER.SESSIONS AS (
    SELECT 
     MEETING_KEY       
    ,SESSION_KEY       
    ,CIRCUIT_KEY       
    ,CIRCUIT_SHORT_NAME
    ,COUNTRY_CODE      
    ,COUNTRY_KEY       
    ,COUNTRY_NAME      
    ,DATE_END          
    ,DATE_START        
    ,GMT_OFFSE         
    ,LOCATION          
    ,SESSION_NAME      
    ,SESSSION_TYPE     
    ,YEAR
    FROM F1_ANALYTICS.BRONZE.SESSIONS

);

--MEETINGS TABLE CLEANUP  

CREATE OR REPLACE TABLE F1_ANALYTICS.SILVER.MEETINGS_SEASON_2026
AS(
    SELECT  
     CIRCUIT_KEY          
    ,CIRCUIT_INFO_URL     
    ,CIRCUIT_IMAGE        
    ,CIRCUIT_SHORT_NAME   
    ,COUNTRY_CODE         
    ,COUNTRY_FLAG         
    ,COUNTRY_KEY          
    ,COUNTRY_NAME         
    ,DATE_END             
    ,DATE_START           
    ,GMT_OFFSET           
    ,LOCATION             
    ,MEETING_KEY          
    ,MEETING_NAME         
    ,MEETING_OFFICIAL_NAME
    ,YEAR      
    FROM F1_ANALYTICS.BRONZE.MEETINGS

);


