create OR REPLACE table current_qualification_result_table_snapshot as
(
select 
TABLE_NAME
,COLUMN_NAME
,DATA_TYPE
 from F1_ANALYTICS.INFORMATION_SCHEMA.COLUMNS where TABLE_CATALOG = 'F1_ANALYTICS' and TABLE_SCHEMA = 'SILVER');

SELECT * FROM CURRENT_QUALIFICATION_RESULT_TABLE_SNAPSHOT;

ALTER TABLE F1_ANALYTICS.SILVER.QUALIFYING_RESULTS ADD COLUMN DNF_REASON TEXT;

SELECT * FROM F1_ANALYTICS.SILVER.QUALIFYING_RESULTS;

CREATE TABLE F1_ANALYTICS.BRONZE.DDL_C_LOGS (
     TABLE_NAME STRING 
    ,COLUMN_NAME STRING 
    ,OPERATION_MAD STRING 
    ,OLD_DATA_TYPE STRING 
    ,NEW_DATA_TYPE STRING 
    ,CHANGE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    ,CHANGED_BY STRING
);  

SELECT
C.TABLE_NAME
,C.COLUMN_NAME
,'ADDED' AS CHANGE_TYPE
,NULL AS OLD_DATA_TYPE
,C.DATA_TYPE AS NEW_DATA_TYPE
,CHANGE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
 FROM F1_ANALYTICS.INFORMATION_SCHEMA.COLUMNS C 
LEFT JOIN F1_ANALYTICS.GOLD.CURRENT_QUALIFICATION_RESULT_TABLE_SNAPSHOT S
ON C.TABLE_NAME = S.TABLE_NAME
AND C.COLUMN_NAME = S.COLUMN_NAME
WHERE  TABLE_CATALOG = 'F1_ANALYTICS' and TABLE_SCHEMA = 'SILVER'


create or replace procedure track_ddl_changes()
RETURNS STRING 
LANGUAGE SQL 
AS 
$$
BEGIN
    INSERT INTO DDL_CHANGES_LOG
    SELECT 
          C.TABLE_NAME
        , C.COLUMN_NAME
        , 'MODIFIED' AS CHANGE_TYPE
        ,
        FROM 
        INFORMATION_SCHEMA.SCHEMA.COLUMNS C 
        JOIN CURRENT_QUALIFICATION_RESULT_TABLE_SNAPSHOT S 
        ON C.TABLE_NAME = S.TABLE_NAME
        AND C.COLUMN_NAME = S.COLUMN_NAME

        
END
            